App\Domain\Contacts:
    type: entity
    table: contacts
    indexes:
        IDX_33401573A76ED395:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        email:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        phoneNumber:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: phone_number
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }