App\Domain\Accounts:
    type: entity
    table: accounts
    indexes:
        IDX_CAC89EACA76ED395:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        login:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: login_
        hashedpassword:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }